version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.10

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest --junitxml=test-results/junit.xml --cov=src --cov-report=xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  version: 2
  test_and_lint:
    jobs:
      - test
