[format]

quote-style = "double"
indent-style = "space"
line-ending = "lf"

[lint]
# Enable all available checks
select = ["ALL"]

# Disable specific rules (explain in comments)
ignore = [
    "E501", # Ignore line length
    "D203", # Conflicts with D211 
    "D213",  # Conflicts with D212
    "PLR0913", #Too many arguments in function, sometimes needed for clarity
    "FBT001", #not useful in many cases
    "FBT002"] #not useful in many cases

