version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.12 
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Install UV
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh

      - run:
          name: Create Virtual Environment & Install Dependencies
          command: |
            uv venv
            . .venv/bin/activate
            uv pip install pytest pytest-cov mypy ruff coverage nose2 nose2[coverage] nose2[junitxml]

      - run:
          name: Run Tests & Generate Coverage Report
          command: |
            . .venv/bin/activate
            pytest --junitxml=test-results/results.xml --cov=src --cov-report=xml --cov-report=html

      - run:
          name: Run Nose2 Tests & Generate Coverage Report
          command: |
            . .venv/bin/activate
            nose2 --junit-xml --with-coverage --coverage-report xml --coverage-report html -s nose2_tests

      - run:
          name: Run linters
          command: ruff check .
          
      - run:
          name: Static analysis
          command: mypy .

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: htmlcov
          destination: test-coverage  # makes the report browsable in CircleCI UI

workflows:
  version: 2
  test_pipeline:
    jobs:
      - test
